# Generated by Django 5.1.2 on 2024-11-01 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_blooddonor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blooddonor',
            name='user',
        ),
        migrations.AddField(
            model_name='blooddonor',
            name='name',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
        migrations.AlterField(
            model_name='blooddonor',
            name='blood_group',
            field=models.CharField(max_length=5),
        ),
    ]
